[package]
name = "rustyfish"
version = "0.1.0"
authors = ["Tom Richardson <tgrkzus@gmail.com>"]

[lib]
name = "rustyfish"
path = "src/rust/lib.rs"
crate-type = ["dylib"]

[dependencies]
piston_window = "0.70.0"
